"""Scalable probabilistic surrogate model + agentic safety wrapper for the
HTGR telemetry generated by ``data_pipeline.py``.

Architecture
------------
1. Preprocessing: pandas ingestion of ``data/htgr_telemetry.csv``,
   operational-input / target separation, ``StandardScaler`` feature
   scaling (fit on train only).
2. Scalable probabilistic modeling: a full ``GaussianProcessRegressor`` is
   O(N^3) in training-set size, which stops scaling once you're generating
   tens of thousands of Monte Carlo rows. Instead each target gets a
   ``Pipeline(StandardScaler -> Nystroem(RBF) -> BayesianRidge)``: the
   Nystroem step approximates the RBF kernel's feature map with a small
   number of random components (O(N * n_components^2) instead of O(N^3)),
   and BayesianRidge then does closed-form Bayesian linear regression on
   top of that feature map - which is what gives ``predict(..,
   return_std=True)`` a genuine posterior predictive mean AND standard
   deviation, not just a point estimate.
3. ``HTGRAgent``: a plain-Python decision layer around the trained
   surrogate. It queries the model for a candidate operating point and
   applies explicit conditional logic (safety-margin breach, high model
   uncertainty, and - importantly - an out-of-training-envelope check)
   to decide whether to clear the point or raise a diagnostic.

Honest limitation, stated up front rather than glossed over: unlike a
true GP, a linear Bayesian model on a *fixed, global* random feature map
does not reliably inflate its predictive std the further a query point
gets from the training data - Nystroem features are not guaranteed to
decorrelate smoothly with distance the way an exact RBF kernel does. So
``HTGRAgent`` does NOT rely on the model's self-reported std alone for
out-of-distribution detection; it also runs an explicit, deterministic
feature-bounds check against the training envelope. Both signals feed the
same decision, but they catch different failure modes.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from sklearn.kernel_approximation import Nystroem
from sklearn.linear_model import BayesianRidge
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "htgr_telemetry.csv"
MODELS_DIR = Path(__file__).resolve().parent.parent / "models"
MODEL_PATH = MODELS_DIR / "htgr_surrogate.joblib"

FEATURE_COLUMNS = [
    "helium_mass_flow_kgs",
    "coolant_inlet_temp_K",
    "rho_insertion",
    "rho_step_time_s",
    "turbine_p_in_Pa",
    "turbine_p_back_Pa",
    "turbine_eta_is",
]
TARGET_COLUMNS = ["peak_fuel_temp_K", "turbine_work_MW"]

PARAM_GRID = {
    "nystroem__gamma": [1e-3, 1e-2, 1e-1, 1.0],
    "nystroem__n_components": [100, 200, 300],
}

RANDOM_STATE = 0
FUEL_TEMP_SAFETY_MARGIN_K = 1650.0
CONFIDENCE_Z = 2.0  # ~95% one-sided upper bound: mean + Z * std

# Demo scenarios for the agentic-workflow walkthrough (script __main__ and
# notebooks/HTGR_Analysis.ipynb both import these, so the two never drift).
SAFE_SCENARIO_DEMO = {
    "helium_mass_flow_kgs": 110.0,
    "coolant_inlet_temp_K": 605.0,
    "rho_insertion": -0.0005,
    "rho_step_time_s": 100.0,
    "turbine_p_in_Pa": 7.0e6,
    "turbine_p_back_Pa": 4.4e6,
    "turbine_eta_is": 0.89,
}
UNSAFE_SCENARIO_DEMO = {
    "helium_mass_flow_kgs": 70.0,  # below the 78 kg/s training floor -> extrapolation
    "coolant_inlet_temp_K": 652.0,  # near the training ceiling
    "rho_insertion": 0.0029,  # near the training ceiling, strongly positive
    "rho_step_time_s": 60.0,
    "turbine_p_in_Pa": 7.6e6,
    "turbine_p_back_Pa": 4.9e6,
    "turbine_eta_is": 0.91,
}


# ---------------------------------------------------------------------------
# 1. Data ingestion & preprocessing
# ---------------------------------------------------------------------------
def load_telemetry(path: Path = DATA_PATH) -> pd.DataFrame:
    df = pd.read_csv(path)
    df = df[df["solver_success"]].reset_index(drop=True)
    return df


def make_pipeline(gamma: float = 0.1, n_components: int = 200) -> Pipeline:
    """StandardScaler -> Nystroem(RBF) -> BayesianRidge.

    This is the scalable stand-in for a full GP: BayesianRidge gives a
    closed-form posterior (mean + std) over the Nystroem-approximated
    kernel feature space in O(N * n_components^2) instead of a GP's
    O(N^3) Cholesky factorisation of the full kernel matrix.
    """
    return Pipeline(
        [
            ("scaler", StandardScaler()),
            ("nystroem", Nystroem(kernel="rbf", gamma=gamma, n_components=n_components, random_state=RANDOM_STATE)),
            ("regressor", BayesianRidge()),
        ]
    )


# ---------------------------------------------------------------------------
# 2. Scalable probabilistic modeling
# ---------------------------------------------------------------------------
@dataclass
class TargetModel:
    """A trained surrogate for one target, plus the metadata the agent
    needs to reason about its own reliability."""

    name: str
    pipeline: Pipeline
    best_params: dict[str, Any]
    cv_r2: float
    test_r2: float
    test_rmse: float
    test_mean_std: float
    test_coverage_95: float
    uncertainty_threshold: float  # data-driven "std is too high" cutoff


@dataclass
class HTGRSurrogate:
    """Bundles one TargetModel per target column plus the training feature
    envelope, so out-of-distribution queries can be flagged deterministically."""

    targets: dict[str, TargetModel] = field(default_factory=dict)
    feature_bounds: dict[str, tuple[float, float]] = field(default_factory=dict)

    def fit(self, df: pd.DataFrame) -> "HTGRSurrogate":
        x = df[FEATURE_COLUMNS]
        self.feature_bounds = {col: (float(x[col].min()), float(x[col].max())) for col in FEATURE_COLUMNS}

        for target in TARGET_COLUMNS:
            y = df[target]
            x_train, x_test, y_train, y_test = train_test_split(
                x, y, test_size=0.2, random_state=RANDOM_STATE
            )

            search = GridSearchCV(
                make_pipeline(), PARAM_GRID, cv=5, scoring="r2", n_jobs=-1
            )
            search.fit(x_train, y_train)
            best_pipeline: Pipeline = search.best_estimator_

            y_pred, y_std = best_pipeline.predict(x_test, return_std=True)
            test_r2 = r2_score(y_test, y_pred)
            test_rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))
            coverage = float(np.mean(np.abs(y_test.to_numpy() - y_pred) <= CONFIDENCE_Z * y_std))
            mean_std = float(np.mean(y_std))
            # Data-driven "uncertainty is too high" cutoff: mean + 2*std of
            # the held-out predictive std itself, i.e. flag queries whose
            # model uncertainty is unusually large relative to what the
            # model normally reports on in-distribution data.
            uncertainty_threshold = mean_std + 2.0 * float(np.std(y_std))

            self.targets[target] = TargetModel(
                name=target,
                pipeline=best_pipeline,
                best_params=search.best_params_,
                cv_r2=float(search.best_score_),
                test_r2=float(test_r2),
                test_rmse=test_rmse,
                test_mean_std=mean_std,
                test_coverage_95=coverage,
                uncertainty_threshold=uncertainty_threshold,
            )
        return self

    def predict(self, features: dict[str, float]) -> dict[str, tuple[float, float]]:
        """Query every target model for one operating point.
        Returns {target_name: (mean, std)}.
        """
        x = pd.DataFrame([{col: features[col] for col in FEATURE_COLUMNS}])
        out = {}
        for name, target_model in self.targets.items():
            mean, std = target_model.pipeline.predict(x, return_std=True)
            out[name] = (float(mean[0]), float(std[0]))
        return out

    def out_of_bounds_features(self, features: dict[str, float]) -> list[str]:
        """Deterministic extrapolation guard: which inputs fall outside the
        training envelope (see module docstring for why this exists
        alongside, not instead of, the model's self-reported std)."""
        flagged = []
        for col in FEATURE_COLUMNS:
            lo, hi = self.feature_bounds[col]
            if not (lo <= features[col] <= hi):
                flagged.append(col)
        return flagged


# ---------------------------------------------------------------------------
# 3. Agentic workflow
# ---------------------------------------------------------------------------
@dataclass
class AgentReport:
    scenario: dict[str, float]
    status: str  # "NOMINAL" | "UNCERTAIN" | "UNSAFE"
    predictions: dict[str, tuple[float, float]]
    flags: list[str]
    recommendations: list[str]


class HTGRAgent:
    """Autonomously evaluates candidate HTGR operating points against the
    trained surrogate and decides whether they're safe to recommend,
    flags them as statistically unreliable, or flags them as unsafe -
    with a root-cause-style diagnostic explaining why.
    """

    def __init__(
        self,
        surrogate: HTGRSurrogate,
        safety_margin_k: float = FUEL_TEMP_SAFETY_MARGIN_K,
        confidence_z: float = CONFIDENCE_Z,
    ) -> None:
        self.surrogate = surrogate
        self.safety_margin_k = safety_margin_k
        self.confidence_z = confidence_z

    def _recommend(self, scenario: dict[str, float]) -> list[str]:
        """Simple domain-knowledge heuristics (core_thermals.m energy
        balance: more flow / cooler inlet / less positive reactivity ->
        lower fuel temperature) for how to pull a hot scenario back down."""
        recs = []
        lo, hi = self.surrogate.feature_bounds["helium_mass_flow_kgs"]
        if scenario["helium_mass_flow_kgs"] < (lo + hi) / 2:
            recs.append("Increase helium_mass_flow_kgs to improve core cooling.")
        if scenario["rho_insertion"] > 0:
            recs.append("Reduce the positive rho_insertion (less reactivity added).")
        lo, hi = self.surrogate.feature_bounds["coolant_inlet_temp_K"]
        if scenario["coolant_inlet_temp_K"] > (lo + hi) / 2:
            recs.append("Lower coolant_inlet_temp_K (more pre-cooler duty upstream).")
        return recs

    def evaluate(self, scenario: dict[str, float]) -> AgentReport:
        predictions = self.surrogate.predict(scenario)
        oob_features = self.surrogate.out_of_bounds_features(scenario)

        flags: list[str] = []
        status = "NOMINAL"

        fuel_mean, fuel_std = predictions["peak_fuel_temp_K"]
        fuel_upper_bound = fuel_mean + self.confidence_z * fuel_std
        fuel_threshold = self.surrogate.targets["peak_fuel_temp_K"].uncertainty_threshold

        if oob_features:
            status = "UNCERTAIN"
            flags.append(
                f"EXTRAPOLATION RISK: {', '.join(oob_features)} fall outside the training "
                "envelope - the surrogate's self-reported std is not trustworthy here "
                "(Nystroem+BayesianRidge doesn't guarantee uncertainty grows with distance "
                "from training data the way a true GP does)."
            )

        if fuel_std > fuel_threshold:
            status = "UNCERTAIN" if status == "NOMINAL" else status
            flags.append(
                f"HIGH MODEL UNCERTAINTY on peak_fuel_temp_K: std={fuel_std:.1f} K exceeds "
                f"the data-driven threshold of {fuel_threshold:.1f} K."
            )

        if fuel_upper_bound > self.safety_margin_k:
            status = "UNSAFE"
            flags.append(
                f"SAFETY MARGIN BREACH: predicted peak fuel temperature "
                f"{fuel_mean:.1f} K (+{self.confidence_z:.0f}sigma -> {fuel_upper_bound:.1f} K) "
                f"exceeds the {self.safety_margin_k:.0f} K limit."
            )

        recommendations = self._recommend(scenario) if status != "NOMINAL" else []

        return AgentReport(
            scenario=scenario,
            status=status,
            predictions=predictions,
            flags=flags,
            recommendations=recommendations,
        )

    @staticmethod
    def print_report(report: AgentReport) -> None:
        fuel_mean, fuel_std = report.predictions["peak_fuel_temp_K"]
        work_mean, work_std = report.predictions["turbine_work_MW"]

        print(f"\n{'=' * 70}")
        print(f"HTGRAgent verdict: {report.status}")
        print(f"{'=' * 70}")
        print("Scenario:")
        for k, v in report.scenario.items():
            print(f"  {k:24s} = {v}")
        print(f"\nPredicted peak_fuel_temp_K : {fuel_mean:8.2f}  (std {fuel_std:6.2f})")
        print(f"Predicted turbine_work_MW  : {work_mean:8.2f}  (std {work_std:6.2f})")

        if report.flags:
            print("\nRoot-cause diagnostics:")
            for f in report.flags:
                print(f"  - {f}")
        if report.recommendations:
            print("\nRecommended adjustments:")
            for r in report.recommendations:
                print(f"  - {r}")
        if report.status == "NOMINAL":
            print("\nNo issues detected - scenario cleared for the fuel-temperature safety check.")


# ---------------------------------------------------------------------------
# 4. Execution block
# ---------------------------------------------------------------------------
def main() -> HTGRAgent:
    if not DATA_PATH.exists():
        print(f"error: {DATA_PATH} not found - run data_pipeline.py first.", file=sys.stderr)
        sys.exit(1)

    df = load_telemetry()
    print(f"Loaded {len(df)} successful runs from {DATA_PATH.name}")
    print(f"Features: {FEATURE_COLUMNS}")
    print(f"Targets:  {TARGET_COLUMNS}\n")

    surrogate = HTGRSurrogate().fit(df)

    print(f"{'Target':<20s}{'CV R2':>10s}{'Test R2':>10s}{'Test RMSE':>12s}{'Mean std':>10s}{'95% cov.':>10s}")
    for name, tm in surrogate.targets.items():
        print(
            f"{name:<20s}{tm.cv_r2:10.4f}{tm.test_r2:10.4f}{tm.test_rmse:12.4f}"
            f"{tm.test_mean_std:10.4f}{tm.test_coverage_95:10.2%}"
        )
        print(f"    best params: {tm.best_params}")

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(surrogate, MODEL_PATH)
    print(f"\nSaved trained surrogate to {MODEL_PATH}")

    agent = HTGRAgent(surrogate)

    print("\n\n### Demo 1: a moderate, in-distribution operating point ###")
    agent.print_report(agent.evaluate(SAFE_SCENARIO_DEMO))

    print("\n\n### Demo 2: low flow + hot inlet + strong positive reactivity ###")
    agent.print_report(agent.evaluate(UNSAFE_SCENARIO_DEMO))

    return agent


if __name__ == "__main__":
    main()
